#include "stm32f103xb.h"

int main(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN | RCC_APB2ENR_IOPAEN;

	GPIOA->CRH |= GPIO_CRH_CNF8_1;
	GPIOA->CRH &= ~GPIO_CRH_CNF8_0;

	GPIOA->ODR |= GPIO_ODR_ODR8;

	TIM1->CCMR1 = TIM_CCMR1_CC1S_0;
	TIM1->CCER = TIM_CCER_CC1E;

	TIM1->PSC = UINT16_MAX;
	TIM1->ARR = UINT16_MAX;

	TIM1->CR1 = TIM_CR1_CEN;

    while(1);
}
