/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103xb.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void){
	 RCC->APB2ENR = RCC_APB2ENR_IOPAEN;

	 GPIOA->CRL |= GPIO_CRL_MODE5_1;
	 GPIOA->CRL &= ~GPIO_CRL_CNF5_0;

	 volatile uint32_t delay;
	 while(1){
		 GPIOA->ODR |= GPIO_ODR_ODR5;
		 for(delay = 100000; delay; delay--){};

		 GPIOA->ODR &= ~GPIO_ODR_ODR5;
		 for(delay = 100000; delay; delay--){};
	 } /* while(1) */
} /* main */
